// components/admin/students/components/dialogs/AddStudentDialog.tsx

'use client'

import { useState } from 'react'
import { toast } from 'sonner'
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from '@/components/ui/dialog'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Badge } from '@/components/ui/badge'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select'
import { UserPlus, Loader2, Eye, Hash, Fingerprint } from 'lucide-react'
import { StudentFormData, Credentials } from '../../types'
import {
  CLASSES,
  DEPARTMENTS,
  GENDERS,
  INITIAL_FORM_DATA,
  generateAdmissionYears,
} from '../../constants'
import { generateEmailPreview } from '../../utils'

interface AddStudentDialogProps {
  onCreateStudent: (data: StudentFormData) => Promise<Credentials | null>
  onCredentialsGenerated: (credentials: Credentials) => void
  isSubmitting: boolean
}

export function AddStudentDialog({
  onCreateStudent,
  onCredentialsGenerated,
  isSubmitting,
}: AddStudentDialogProps) {
  const [open, setOpen] = useState(false)
  const admissionYears = generateAdmissionYears()
  const [formData, setFormData] = useState<StudentFormData>(INITIAL_FORM_DATA)

  const handleSubmit = async () => {
    // Validate required fields
    if (!formData.first_name || !formData.last_name || !formData.class) {
      toast.error('Please fill in all required fields (First name, Last name, Class)')
      return
    }

    if (!formData.admission_number) {
      toast.error('Please enter an Admission Number')
      return
    }

    const credentials = await onCreateStudent(formData)
    if (credentials) {
      setOpen(false)
      onCredentialsGenerated(credentials)
      setFormData(INITIAL_FORM_DATA)
    }
  }

  const updateField = <K extends keyof StudentFormData>(
    key: K,
    value: StudentFormData[K]
  ) => {
    setFormData(prev => ({ ...prev, [key]: value }))
  }

  return (
    <Dialog open={open} onOpenChange={setOpen}>
      <DialogTrigger asChild>
        <Button className="bg-gradient-to-r from-primary to-secondary shadow-lg hover:shadow-xl transition-shadow">
          <UserPlus className="mr-2 h-4 w-4" />
          Add Student
        </Button>
      </DialogTrigger>

      <DialogContent className="sm:max-w-[650px] max-h-[90vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle>Add New Student</DialogTitle>
          <DialogDescription>
            Fill in student details. <strong>VIN ID</strong> (format: VIN-STD-YYYY-XXXX) will be
            auto-generated by the system. <strong>Admission Number</strong> must be entered manually.
          </DialogDescription>
        </DialogHeader>

        <div className="space-y-5 py-4">
          {/* ============================================ */}
          {/* SECTION 1: NAME FIELDS */}
          {/* ============================================ */}
          <div>
            <h4 className="text-sm font-semibold mb-3 flex items-center gap-2">
              <span className="h-1.5 w-1.5 rounded-full bg-primary" />
              Student Name
            </h4>
            <div className="grid grid-cols-3 gap-3">
              <div>
                <Label>First Name *</Label>
                <Input
                  value={formData.first_name}
                  onChange={e => updateField('first_name', e.target.value)}
                  placeholder="e.g., OYEBANJI"
                  className="mt-1"
                />
              </div>
              <div>
                <Label>Middle Name</Label>
                <Input
                  value={formData.middle_name}
                  onChange={e => updateField('middle_name', e.target.value)}
                  placeholder="Other names"
                  className="mt-1"
                />
              </div>
              <div>
                <Label>Last Name *</Label>
                <Input
                  value={formData.last_name}
                  onChange={e => updateField('last_name', e.target.value)}
                  placeholder="e.g., GLORY"
                  className="mt-1"
                />
              </div>
            </div>
          </div>

          {/* ============================================ */}
          {/* SECTION 2: PERSONAL INFO (Portal & Report Only) */}
          {/* ============================================ */}
          <div>
            <h4 className="text-sm font-semibold mb-3 flex items-center gap-2">
              <span className="h-1.5 w-1.5 rounded-full bg-amber-500" />
              Personal Information
              <Badge variant="outline" className="text-xs ml-2">Portal &amp; Report Only</Badge>
            </h4>
            <div className="grid grid-cols-2 gap-4">
              {/* Gender */}
              <div>
                <Label>Gender *</Label>
                <Select
                  value={formData.gender}
                  onValueChange={v => updateField('gender', v as 'male' | 'female' | 'other')}
                >
                  <SelectTrigger className="mt-1">
                    <SelectValue placeholder="Select gender" />
                  </SelectTrigger>
                  <SelectContent>
                    {GENDERS.map(g => (
                      <SelectItem key={g.value} value={g.value}>
                        {g.emoji} {g.label}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>

              {/* Date of Birth */}
              <div>
                <Label>Date of Birth</Label>
                <Input
                  type="date"
                  value={formData.date_of_birth}
                  onChange={e => updateField('date_of_birth', e.target.value)}
                  className="mt-1"
                />
              </div>
            </div>
          </div>

          {/* ============================================ */}
          {/* SECTION 3: ACADEMIC INFO */}
          {/* ============================================ */}
          <div>
            <h4 className="text-sm font-semibold mb-3 flex items-center gap-2">
              <span className="h-1.5 w-1.5 rounded-full bg-blue-500" />
              Academic Information
            </h4>
            <div className="space-y-4">
              {/* Class & Admission Year */}
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <Label>Class *</Label>
                  <Select
                    value={formData.class}
                    onValueChange={v => updateField('class', v)}
                  >
                    <SelectTrigger className="mt-1">
                      <SelectValue placeholder="Select class" />
                    </SelectTrigger>
                    <SelectContent>
                      {CLASSES.map(c => (
                        <SelectItem key={c} value={c}>{c}</SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </div>
                <div>
                  <Label>Admission Year *</Label>
                  <Select
                    value={formData.admission_year.toString()}
                    onValueChange={v => updateField('admission_year', parseInt(v))}
                  >
                    <SelectTrigger className="mt-1">
                      <SelectValue placeholder="Select year" />
                    </SelectTrigger>
                    <SelectContent className="max-h-[200px]">
                      {admissionYears.map(year => (
                        <SelectItem key={year} value={year.toString()}>{year}</SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </div>
              </div>

              {/* Department */}
              <div>
                <Label>Department</Label>
                <Select
                  value={formData.department}
                  onValueChange={v => updateField('department', v)}
                >
                  <SelectTrigger className="mt-1">
                    <SelectValue placeholder="Select department" />
                  </SelectTrigger>
                  <SelectContent>
                    {DEPARTMENTS.map(d => (
                      <SelectItem key={d} value={d}>{d}</SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>
            </div>
          </div>

          {/* ============================================ */}
          {/* SECTION 4: IDENTIFICATION NUMBERS */}
          {/* ============================================ */}
          <div>
            <h4 className="text-sm font-semibold mb-3 flex items-center gap-2">
              <span className="h-1.5 w-1.5 rounded-full bg-emerald-500" />
              Identification Numbers
            </h4>
            <div className="space-y-4">
              {/* ✅ ADMISSION NUMBER - MANUAL INPUT */}
              <div>
                <Label className="flex items-center gap-2">
                  <Hash className="h-4 w-4 text-emerald-600" />
                  Admission Number *
                </Label>
                <Input
                  value={formData.admission_number}
                  onChange={e => updateField('admission_number', e.target.value)}
                  placeholder="e.g., 2025VIN62"
                  className="mt-1 font-mono text-lg"
                />
                <p className="text-xs text-muted-foreground mt-1">
                  Enter manually. Examples: 2025VIN62, 2026VIN02, 2022VIN08
                </p>
                <div className="flex gap-2 mt-1">
                  <Badge variant="secondary" className="text-xs">Portal</Badge>
                  <Badge variant="secondary" className="text-xs">CBT</Badge>
                  <Badge variant="secondary" className="text-xs">Report Card</Badge>
                </div>
              </div>

              {/* ✅ VIN ID - AUTO GENERATED (Read Only Preview) */}
              <div className="bg-slate-100 dark:bg-slate-800 rounded-lg p-3">
                <Label className="flex items-center gap-2 text-muted-foreground">
                  <Fingerprint className="h-4 w-4" />
                  VIN ID (Auto-generated by System)
                </Label>
                <p className="font-mono text-sm text-primary mt-1">
                  {formData.admission_year
                    ? `VIN-STD-${formData.admission_year}-XXXX`
                    : 'VIN-STD-YYYY-XXXX'}
                </p>
                <p className="text-xs text-muted-foreground mt-1">
                  Format: VIN-STD-YYYY-XXXX (System generates the last 4 digits)
                </p>
              </div>
            </div>
          </div>

          {/* ============================================ */}
          {/* SECTION 5: NEXT TERM (Portal & Report Only) */}
          {/* ============================================ */}
          <div>
            <h4 className="text-sm font-semibold mb-3 flex items-center gap-2">
              <span className="h-1.5 w-1.5 rounded-full bg-purple-500" />
              Term Information
              <Badge variant="outline" className="text-xs ml-2">Portal &amp; Report Only</Badge>
            </h4>
            <div>
              <Label>Next Term Begins</Label>
              <Input
                type="date"
                value={formData.next_term_begins}
                onChange={e => updateField('next_term_begins', e.target.value)}
                className="mt-1"
              />
              <p className="text-xs text-muted-foreground mt-1">
                Optional. Displays countdown on student portal and report cards.
              </p>
            </div>
          </div>

          {/* ============================================ */}
          {/* SECTION 6: CONTACT INFO */}
          {/* ============================================ */}
          <div>
            <h4 className="text-sm font-semibold mb-3 flex items-center gap-2">
              <span className="h-1.5 w-1.5 rounded-full bg-gray-500" />
              Contact Information (Optional)
            </h4>
            <div className="grid grid-cols-2 gap-4">
              <div>
                <Label>Phone</Label>
                <Input
                  value={formData.phone}
                  onChange={e => updateField('phone', e.target.value)}
                  placeholder="+234 XXX XXX XXXX"
                  className="mt-1"
                />
              </div>
              <div>
                <Label>Address</Label>
                <Input
                  value={formData.address}
                  onChange={e => updateField('address', e.target.value)}
                  placeholder="Home address"
                  className="mt-1"
                />
              </div>
            </div>
          </div>

          {/* ============================================ */}
          {/* CREDENTIALS PREVIEW */}
          {/* ============================================ */}
          <div className="bg-gradient-to-br from-slate-100 to-blue-50 dark:from-slate-800 dark:to-blue-950/30 rounded-lg p-4 border space-y-3">
            <p className="text-xs font-semibold text-muted-foreground uppercase tracking-wider">
              Credentials Preview
            </p>
            <div className="space-y-2">
              {/* Email Preview */}
              <div className="flex justify-between items-center">
                <div>
                  <p className="text-xs text-muted-foreground">Email Address</p>
                  <p className="font-mono text-sm">
                    {formData.first_name && formData.last_name
                      ? generateEmailPreview(formData.first_name, formData.last_name)
                      : 'student@vincollins.edu.ng'}
                  </p>
                </div>
                <Badge variant="secondary" className="text-xs">Auto</Badge>
              </div>

              {/* VIN ID Preview */}
              <div className="flex justify-between items-center pt-2 border-t">
                <div>
                  <p className="text-xs text-muted-foreground">VIN ID</p>
                  <p className="font-mono text-sm text-primary">
                    {formData.admission_year
                      ? `VIN-STD-${formData.admission_year}-XXXX`
                      : 'VIN-STD-YYYY-XXXX'}
                  </p>
                </div>
                <Badge variant="secondary" className="text-xs">Auto</Badge>
              </div>

              {/* Admission Number Preview */}
              <div className="flex justify-between items-center pt-2 border-t">
                <div>
                  <p className="text-xs text-muted-foreground">Admission Number</p>
                  <p className="font-mono text-sm font-bold text-emerald-600">
                    {formData.admission_number || '(not set)'}
                  </p>
                </div>
                <Badge variant="outline" className="text-xs">Manual</Badge>
              </div>
            </div>
          </div>

          {/* ============================================ */}
          {/* FIELD VISIBILITY GUIDE */}
          {/* ============================================ */}
          <div className="bg-blue-50 dark:bg-blue-950/20 rounded-lg p-4 border border-blue-200">
            <p className="text-xs font-semibold text-blue-800 mb-3 flex items-center gap-2">
              <Eye className="h-3.5 w-3.5" />
              Field Visibility Reference
            </p>
            <div className="space-y-2 text-xs">
              {/* Admission Number - Visible Everywhere */}
              <div className="flex items-center justify-between bg-white/50 rounded p-2">
                <div className="flex items-center gap-2">
                  <Hash className="h-3 w-3 text-emerald-600" />
                  <span className="font-medium">Admission Number</span>
                </div>
                <div className="flex gap-1">
                  <Badge variant="secondary" className="text-xs">Portal</Badge>
                  <Badge variant="secondary" className="text-xs">CBT</Badge>
                  <Badge variant="secondary" className="text-xs">Report Card</Badge>
                </div>
              </div>

              {/* VIN ID - System Only */}
              <div className="flex items-center justify-between bg-white/50 rounded p-2">
                <div className="flex items-center gap-2">
                  <Fingerprint className="h-3 w-3 text-primary" />
                  <span className="font-medium">VIN ID</span>
                </div>
                <div className="flex gap-1">
                  <Badge variant="outline" className="text-xs">Login</Badge>
                  <Badge variant="outline" className="text-xs">System</Badge>
                </div>
              </div>

              {/* Gender - Portal & Report */}
              <div className="flex items-center justify-between bg-white/50 rounded p-2">
                <div className="flex items-center gap-2">
                  <span className="font-medium">Gender</span>
                </div>
                <div className="flex gap-1">
                  <Badge variant="outline" className="text-xs">Portal</Badge>
                  <Badge variant="outline" className="text-xs">Report Card</Badge>
                </div>
              </div>

              {/* DOB - Portal & Report */}
              <div className="flex items-center justify-between bg-white/50 rounded p-2">
                <div className="flex items-center gap-2">
                  <span className="font-medium">Date of Birth</span>
                </div>
                <div className="flex gap-1">
                  <Badge variant="outline" className="text-xs">Portal</Badge>
                  <Badge variant="outline" className="text-xs">Report Card</Badge>
                </div>
              </div>

              {/* Next Term - Portal & Report */}
              <div className="flex items-center justify-between bg-white/50 rounded p-2">
                <div className="flex items-center gap-2">
                  <span className="font-medium">Next Term Begins</span>
                </div>
                <div className="flex gap-1">
                  <Badge variant="outline" className="text-xs">Portal</Badge>
                  <Badge variant="outline" className="text-xs">Report Card</Badge>
                </div>
              </div>
            </div>
          </div>
        </div>

        <DialogFooter className="gap-2">
          <Button variant="outline" onClick={() => setOpen(false)}>
            Cancel
          </Button>
          <Button
            onClick={handleSubmit}
            disabled={isSubmitting}
            className="bg-gradient-to-r from-primary to-secondary"
          >
            {isSubmitting ? (
              <>
                <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                Creating...
              </>
            ) : (
              <>
                <UserPlus className="mr-2 h-4 w-4" />
                Create Student
              </>
            )}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  )
}