// components/admin/students/utils/index.ts

import { toast } from 'sonner'
import { BulkUploadRow } from '../types'

// ============================================
// NAME & TEXT HELPERS
// ============================================

export const getInitials = (name?: string): string => {
  if (!name) return 'S'
  return name
    .split(' ')
    .map(n => n[0])
    .join('')
    .toUpperCase()
    .slice(0, 2)
}

export const formatFullName = (
  firstName: string,
  lastName: string,
  middleName?: string
): string => {
  const capitalize = (str: string) =>
    str.trim().charAt(0).toUpperCase() + str.trim().slice(1).toLowerCase()

  const first = capitalize(firstName)
  const last = capitalize(lastName)
  const middle = middleName?.trim()

  if (middle) {
    return `${first} ${capitalize(middle)} ${last}`
  }
  return `${first} ${last}`
}

export const normalizeClass = (className: string): string => {
  const upper = className.toUpperCase()
  if (upper.includes('JSS') && upper.includes('1')) return 'JSS 1'
  if (upper.includes('JSS') && upper.includes('2')) return 'JSS 2'
  if (upper.includes('JSS') && upper.includes('3')) return 'JSS 3'
  if (upper.includes('SS') && upper.includes('1')) return 'SS 1'
  if (upper.includes('SS') && upper.includes('2')) return 'SS 2'
  if (upper.includes('SS') && upper.includes('3')) return 'SS 3'
  return className
}

// ============================================
// DATE & TIME HELPERS
// ============================================

export const formatLastSeen = (timestamp?: string): string => {
  if (!timestamp) return 'Never'

  const lastSeen = new Date(timestamp)
  const now = new Date()
  const diffMs = now.getTime() - lastSeen.getTime()
  const diffMins = Math.floor(diffMs / 60000)
  const diffHours = Math.floor(diffMs / 3600000)
  const diffDays = Math.floor(diffMs / 86400000)

  if (diffMins < 1) return 'Just now'
  if (diffMins < 60) return `${diffMins} min${diffMins > 1 ? 's' : ''} ago`
  if (diffHours < 24) return `${diffHours} hour${diffHours > 1 ? 's' : ''} ago`
  if (diffDays < 7) return `${diffDays} day${diffDays > 1 ? 's' : ''} ago`
  return lastSeen.toLocaleDateString()
}

export const getDaysRemaining = (dateString: string): string => {
  const target = new Date(dateString)
  const now = new Date()
  const diffTime = target.getTime() - now.getTime()
  const diffDays = Math.ceil(diffTime / (1000 * 60 * 60 * 24))

  if (diffDays < 0) return 'Term has started'
  if (diffDays === 0) return 'Term begins today!'
  if (diffDays === 1) return 'Term begins tomorrow'
  return `${diffDays} days remaining`
}

export const formatDate = (dateString?: string): string => {
  if (!dateString) return '-'
  return new Date(dateString).toLocaleDateString('en-GB', {
    day: 'numeric',
    month: 'long',
    year: 'numeric',
  })
}

// ============================================
// CLIPBOARD HELPERS
// ============================================

export const copyToClipboard = (text: string, label: string) => {
  navigator.clipboard.writeText(text).then(() => {
    toast.success(`${label} copied to clipboard!`)
  }).catch(() => {
    toast.error('Failed to copy')
  })
}

// ============================================
// EMAIL & VIN ID GENERATION
// ============================================

export const generateEmailPreview = (firstName: string, lastName: string): string => {
  if (!firstName || !lastName) return 'student@vincollins.edu.ng'
  const clean = (str: string) => str.toLowerCase().replace(/[^a-z]/g, '')
  return `${clean(firstName)}.${clean(lastName)}@vincollins.edu.ng`
}

// ✅ VIN ID format: VIN-STD-2026-6453 (Auto-generated by API, shown for reference)
export const generateVINPreview = (year: number): string => {
  if (!year) return 'VIN-STD-YYYY-XXXX'
  return `VIN-STD-${year}-XXXX (auto-generated)`
}

// ============================================
// CSV PARSING
// ============================================

export const parseCSV = (text: string): BulkUploadRow[] => {
  const lines = text.split('\n').filter(line => line.trim())
  if (lines.length === 0) return []

  const headers = lines[0].split(',').map(h => h.trim().toLowerCase())
  const requiredHeaders = ['first_name', 'last_name', 'class']

  const missingHeaders = requiredHeaders.filter(h => !headers.includes(h))
  if (missingHeaders.length > 0) {
    throw new Error(`Missing required columns: ${missingHeaders.join(', ')}`)
  }

  return lines
    .slice(1)
    .map((line, index) => {
      const values = line.split(',').map(v => v.trim())
      const row: any = { _line: index + 2 }
      headers.forEach((header, colIndex) => {
        row[header] = values[colIndex] || ''
      })
      return row as BulkUploadRow
    })
    .filter(row => row.first_name && row.last_name && row.class)
}

// ============================================
// CSV TEMPLATE GENERATION
// ============================================

export const generateCSVTemplate = (): string => {
  const { CSV_HEADERS, CSV_SAMPLE_ROWS } = require('../constants')
  const rows = [CSV_HEADERS.join(','), ...CSV_SAMPLE_ROWS.map((row: any[]) => row.join(','))]
  return rows.join('\n')
}

export const downloadCSVTemplate = () => {
  const csvContent = generateCSVTemplate()
  const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' })
  const url = window.URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = 'student_bulk_upload_template.csv'
  a.click()
  window.URL.revokeObjectURL(url)
}